### ISSUE TITLE
Adress management for the frontend users

### ISSUE THREAD

**Issue by QUIQQER** [QUIQQER/frontend-users#1]
You must create an address management for the frontend users.

What needs to be done:

- The user must be able to perform various actions
    - [x] Create address
    - [x] Delete address
    - [x] Editing an address
    - [x] Various events so that other modules can connect to each other
    - [x] Multilingual: englisch and german
    - [x] Setting: Address management active or inactive
    - [x] User address limit -> max 100

Original Issue: https://dev.quiqqer.com/quiqqer/frontend-users/issues/19

**Comment by dehenne** [comment]
https://github.com/QUIQQER/frontend-users/commit/7d9196ae4b88d73599e9ae57a24330fc0944bad6

**Comment by dehenne** [comment]
https://dev.quiqqer.com/quiqqer/controls/commit/9e601f6471796bc972328f947beb9fef19ce0261

**Comment by dehenne** [comment]
https://github.com/QUIQQER/frontend-users/commit/db4cdacbdc95f2a613627757f713b22a15dda799

**Comment by dehenne** [comment]
https://github.com/QUIQQER/frontend-users/commit/9b7941cd88f32b8b5ff6fb672fbf9fc38fb672b5

**Comment by dehenne** [comment]
https://github.com/QUIQQER/quiqqer/commit/6ddaaf5cf46339d2a675c801d254cd25b3691c9d

**Comment by dehenne** [comment]
https://github.com/QUIQQER/frontend-users/commit/49922783b892934111c7b31b68061f51d7ceab89
